name: AWS RESOURCES DESTRUCTION PIPELINE
on:
  workflow_dispatch:
   
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init -backend-config=../backend.hcl --reconfigure
        working-directory: ./aws_resources

      - name: Terraform Refresh (load state from remote)
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform refresh -input=false
        working-directory: ./aws_resources

      - name: Export Terraform Outputs (Athena Workgroup)
        id: tfoutputs
        working-directory: ./aws_resources
        run: |
          WG_NAME=$(terraform output -raw athena_workgroup_name 2>/dev/null || echo "")
          echo "ATHENA_WORKGROUP=$WG_NAME" >> $GITHUB_ENV
          echo "EXPORT -> $WG_NAME"

      - name: Delete Athena WorkGroup (Safe / Idempotent)
        if: env.ATHENA_WORKGROUP != ''
        run: |
          EXIST=$(aws athena list-work-groups --query "WorkGroups[?Name=='$ATHENA_WORKGROUP']" --output text)
          if [ -n "$EXIST" ]; then
            echo "WorkGroup $ATHENA_WORKGROUP exists - deleting..."
            aws athena delete-work-group \
              --work-group-name "$ATHENA_WORKGROUP" \
              --recursive-delete-option || true
          else
            echo "WorkGroup $ATHENA_WORKGROUP not found - skipped."
          fi

      - name: Terraform Plan
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform plan -out=tfplan -input=false
        working-directory: ./aws_resources

      - name: Terraform Destroy
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform destroy -auto-approve -input=false
        working-directory: ./aws_resources
