name: AWS RESOURCES DESTRUCTION PIPELINE
on:
  workflow_dispatch:
   
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init -backend-config=../backend.hcl --reconfigure
        working-directory: ./aws_resources

       - name: Export Terraform Outputs
        id: tfoutputs
        run: |
          echo "ATHENA_WORKGROUP=$(terraform output -raw athena_workgroup_name)" >> $GITHUB_ENV
        working-directory: ./aws_resources

      - name: Delete Athena WorkGroup Force
        run: |
          aws athena delete-work-group \
            --work-group-name $ATHENA_WORKGROUP \
            --recursive-delete-option || true

      - name: Terraform Plan
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform plan -out=tfplan -input=false
        working-directory: ./aws_resources

      - name: Terraform Destroy
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform destroy -auto-approve -input=false
        working-directory: ./aws_resources
