name: AWS RESOURCES CREATION PIPELINE
on:
  #workflow_dispatch:
  push:
    branches: main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init -backend-config=../backend.hcl --reconfigure
        working-directory: ./aws_resources

      - name: Terraform Plan
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.API_SECRET }}
          TR_VAR_root_role : ${{ secrets.AWS_ROOT_ROLE }}
        run: terraform plan -out=tfplan
        working-directory: ./aws_resources

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -target=module.glue_catalog_utils.aws_lakeformation_data_lake_settings.admins -auto-approve tfplan
        working-directory: ./aws_resources
