name: AWS RESOURCES DESTRUCTION PIPELINE
on:
  workflow_dispatch:
   
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init -backend-config=../backend.hcl --reconfigure
        working-directory: ./aws_resources

      - name: Export Terraform Outputs
        id: tfoutputs
        run: |
          OUTPUT=$(terraform output -raw athena_workgroup_name 2>&1)
          if [[ $? -eq 0 && ! "$OUTPUT" =~ "Warning" && ! "$OUTPUT" =~ "╷" ]]; then
            echo "ATHENA_WORKGROUP=$OUTPUT" >> $GITHUB_ENV
            echo "Athena WorkGroup exported: $OUTPUT"
          else
            echo "No Terraform outputs found, skipping export"
            echo "ATHENA_WORKGROUP=" >> $GITHUB_ENV
          fi
        working-directory: ./aws_resources

      - name: Delete Athena WorkGroup Force
        if: env.ATHENA_WORKGROUP != ''
        run: |
          aws athena delete-work-group \
            --work-group $ATHENA_WORKGROUP \
            --recursive-delete-option

      - name: Terraform Plan
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform plan -out=tfplan -input=false
        working-directory: ./aws_resources

      - name: Terraform Destroy
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        run: terraform destroy -auto-approve -input=false
        working-directory: ./aws_resources
